// <auto-generated />
using System;
using Festivo.CrowdMonitorService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Festivo.CrowdMonitorService.Migrations
{
    [DbContext(typeof(CrowdDbContext))]
    partial class CrowdDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Festivo.CrowdMonitorService.Data.Entities.Occupancy", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("Current")
                        .HasColumnType("bigint");

                    b.Property<long>("Limit")
                        .HasColumnType("bigint");

                    b.Property<long>("WarningThreshold")
                        .HasColumnType("bigint");

                    b.HasKey("EventId", "Type");

                    b.ToTable("Occupancies", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
